// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgqOnaAYYRqK80dHWu058M8V37dqLUvL4',
    appId: '1:425571269096:web:14969636a9cc61b071cc5d',
    messagingSenderId: '425571269096',
    projectId: 'login-a7edf',
    authDomain: 'login-a7edf.firebaseapp.com',
    storageBucket: 'login-a7edf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJxUG87kWSQ2gUbcN__NFPtaFkefJtiL4',
    appId: '1:425571269096:android:fcf68d7de176b9da71cc5d',
    messagingSenderId: '425571269096',
    projectId: 'login-a7edf',
    storageBucket: 'login-a7edf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfUEl7RVZiPZuoXzKrZ3Endq7Z-deiHHA',
    appId: '1:425571269096:ios:826131baf06b4ab771cc5d',
    messagingSenderId: '425571269096',
    projectId: 'login-a7edf',
    storageBucket: 'login-a7edf.appspot.com',
    iosClientId: '425571269096-im6vbcb7lmodpso8pes0fjkevi9hjqe5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfUEl7RVZiPZuoXzKrZ3Endq7Z-deiHHA',
    appId: '1:425571269096:ios:b5e39eeb03c2b89071cc5d',
    messagingSenderId: '425571269096',
    projectId: 'login-a7edf',
    storageBucket: 'login-a7edf.appspot.com',
    iosClientId: '425571269096-1ar6klips8ljmvukb9enqo7q05rnqkr9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
